### ISSUE TITLE
convert to using cogent3 plotly

### ISSUE THREAD

**Issue by GavinHuttley** [HuttleyLab/MutationMotif#1]
The attached directory shows plotting for 2 different subcommands of mutation_motif.

Just install this repo as editable in your `c3dev` conda environment. The `.log` files in the sub directories show how the command used to generate the pdf in each subdirectory.

[mm_draw.zip](https://github.com/HuttleyLab/MutationMotif/files/4069396/mm_draw.zip)

**Comment by u6052029** [comment]
Started conversion to Plotly, got a figure of one of the plots as pdf; however, the other plot is not visible.

Reminder to self:
Attempt to build a multi-plot of just letters in Jupyter lab using the example letters plot as a base.

**Comment by GavinHuttley** [comment]
fixed in db988c9071081425cb1cffd5a4c23890394c5aba
