### ISSUE TITLE
ImportError: cannot import name 'chisqprob' from 'cogent3.maths.stats'

### ISSUE THREAD

**Issue by lilei1** [HuttleyLab/MutationMotif#44]
I've got the error when I ran "simple_analysis". By the way, I used python 3.8 and scipy 1.10.1. How can I fix this issue?

Traceback (most recent call last):
  File "/panfs/jay/groups/9/morrellp/llei/.conda/envs/mut_motif/bin/mutation_analysis", line 5, in <module>
    from mutation_motif.mutation_analysis import main
  File "/home/morrellp/llei/.conda/envs/mut_motif/lib/python3.8/site-packages/mutation_motif/mutation_analysis.py", line 9, in <module>
    from cogent3.maths.stats import chisqprob
ImportError: cannot import name 'chisqprob' from 'cogent3.maths.stats' (/home/morrellp/llei/.conda/envs/mut_motif/lib/python3.8/site-packages/cogent3/maths/stats/__init__.py)
rename: *.pdf: rename to *_AtoC_NaN_filter_plate.0_24.gatk.hf.sc.recode.winFlank15bp.txt_NaN.SNPs.pdf failed: No such file or directory
rename: *.json: rename to *_AtoC_NaN_filter_plate.0_24.gatk.hf.sc.recode.winFlank15bp.txt_NaN.SNPs.json failed: No such file or directory
rename: *.txt: rename to *_AtoC_NaN_filter_plate.0_24.gatk.hf.sc.recode.winFlank15bp.txt_NaN.SNPs.txt failed: No such file or directory

**Comment by GavinHuttley** [comment]
Thanks for reporting this! The upstream library has changed, I'll post a fix in a few hours.

**Comment by GavinHuttley** [comment]
This issue is fixed. You can now also use up to python 3.10 and we will support 3.11 as soon as cogent3 does

**Comment by lilei1** [comment]
Should I only rerun this?
```
python -m pip install git+https://github.com/HuttleyLab/MutationMotif.git@develop#egg=mutation_motif

```

**Comment by GavinHuttley** [comment]
To be safe, I would uninstall it first
```
$ python -m pip uninstall mutation_motif
```
then rerun that command
